name: Bingo
version: ${project.version}
main: github.xathviar.plugins.bingo.Startup
api-version: "1.13"
authors: [xathviar, Laserlord]
commands:
  bb:
    description: shortform for  bingo board
  bingo:
    description: bingo for the current player
  bingo start:
    description: start a new game of bingo
  bingo reset:
    description: resets the items you alread collected
  bingo board:
    description: displays the current bingo board
  bingo pause:
    description: lets you pause the current game
  bingo resume:
    description: lets you resume the paused game
  bingo custom:
    description: lets you create a custom bingo board
